### ISSUE TITLE
Orm.is_modified() should be True only if the new value set is different than the old value.

### ISSUE THREAD

**Issue by fotopher** [firstopinion/prom#27]
This is a debatable addition to prom. The problem that prompted this issue is /customer/update is called with timezone data every time the iOS app is opened. When new code was added to update Salesforce whenever the User is updated, this caused the Salesforce queue to grow faster than the requests could be processed.

So, should this kind of work be done by the client or the orm library? The decision is yours!

**Comment by Jaymon** [comment]
As we discussed in the office, this isn't something the Orm should worry about, so I'm not going to either
