### ISSUE TITLE
nit: Indicies vs Indexes

### ISSUE THREAD

**Issue by sughodke** [firstopinion/prom#34]
:rage: YARGH!  Just venting some frustration typing indexes.  Feel free to close this issue.

(Hrm, this article does state that both are valid.  http://grammarist.com/usage/indexes-indices/)

https://github.com/firstopinion/prom/blob/master/prom/config.py#L171

**Comment by Jaymon** [comment]
My completely unscientific poll of Google:

|Google Search     | Results |
|:---------|----------:|
|indices site:sqlite.org|1,690|
|indices site:postgresql.org|2,120|
|indices site:dev.mysql.com|218|
|indexes site:dev.mysql.com|11,300|
|indexes site:postgresql.org|37,300|
|indexes site:sqlite.org|3,960|

I declare `indexes` the winner :)
